### ISSUE TITLE
Header uses too much space

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#1028]
Header currently steals as much as 72px. I think 24-32px would be fine. Vertical space is precious.

**Comment by marcopeereboom** [comment]
@MariaPleshkova is the redesign addressing this?

**Comment by dornelasN** [comment]
Hi, I don't know about the redesign addressing this. But @fernandoabolafio talked to me about looking at the "good-first-issues"'s and I was checking out this one.

I tried the 32px as requested. It looked a bit small to me. I have two screen shots with 32px and with 45px below so you guys can compare. I decided to go with 45px because the https://explorer.dcrdata.org/ uses that header size.

Let me know if you guy think it's better with 32px like @xaur requested or the 45px.

![32px header](https://user-images.githubusercontent.com/9327569/56530654-21fffd80-6529-11e9-90eb-1c042d1fb07c.png)
![45px header](https://user-images.githubusercontent.com/9327569/56530655-21fffd80-6529-11e9-8252-5a1ed3709ed3.png)

**Comment by xaur** [comment]
I think small one-constant tweaks can be done without waiting for a large redesign. 32px could work with some tweaks to logo, font and item placement. But 45px looks ok too for me.

**Comment by dornelasN** [comment]
I wasn't sure if I was supposed to tweak the items on the header, but I could try playing around with them if you prefer, or could just send it with 45px. What is best?

**Comment by xaur** [comment]
@dornelasN I suggest to check with devs first to avoid wasted work.

**Comment by dornelasN** [comment]
Sure, any thought on these @fernandoabolafio?
