### ISSUE TITLE
[redesign] Layout issues

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1425]
As pointed by @behindtext we have room for some improvements in the overall layout of the website:

> what i think definitely needs improvement - vertical size of header is too large, it pushes content down and just eats up space
the div that contains "Proposal Details" in particular - it just wastes space
the spacing between that proposal details div and the content div below it also eats up space
the left and right margins eat up space that should be used for content
the right div that has the About Politeia info really needs to go away - it just wastes space
that div has some utility and doesn't look so out of place on the landing page that lists proposals
on the proposal details page, it is a total waste, imo
i think the font size could come down a bit without causing legibility problems

Another thing pointed out by @davecgh is:
>  The other thing that stands out to me is the lack of a strong visual indicator between the entries to clearly delineate them (e.g. a drop shadow like the old one has is enough).

Another important thing is that people are claiming that they would rather use the old website than the new one for the desktop. One of the main reasons is the centralization of content. Looks like that having the content always aligned to left margin is a common preference.

@MariaPleshkova @linnutee

**Comment by tiagoalvesdulce** [comment]
We should definitely think about improving the pigui on a large monitor with high resolution. Like @davecgh said on matrix. Example:

New pigui:

![image](https://user-images.githubusercontent.com/13955303/65261865-8b3b6b00-dadf-11e9-84e3-826d96ee0bee.png)

Old pigui:

![image](https://user-images.githubusercontent.com/13955303/65261878-91314c00-dadf-11e9-9db8-6f9f7846f926.png)

**Comment by MariaPleshkova** [comment]
Regarding wide screens, I think we can just always use the same left and right margins for the content and stretch proposal cards. Like this:
![image](https://user-images.githubusercontent.com/8841018/65411040-8125af00-ddf4-11e9-9c02-8158275b3d60.png)

What do you think?

**Comment by fernandoabolafio** [comment]
@MariaPleshkova  I think it could work and it's reasonably easy. However we're just "wasting" space by stretching those containers with such a small amount of information.  Another option suggested was to use a grid:
For example:
![Screen Shot 2019-09-23 at 13 33 51](https://user-images.githubusercontent.com/14864439/65422493-eaaeb900-de06-11e9-9fbb-5e6057c42a5d.png)

**Comment by fernandoabolafio** [comment]
got it @MariaPleshkova! I think that in this specific situation of Politeia, the website is targeting developers and people involved with technology so that I would expect a reasonable number of people to be using Politeia on larger screen sizes. Anyway, I think we can give it a try on stretching the cards by adding fixed margins and iterate it again.
What about the other points mentioned:
1. "vertical size of header is too large, it pushes content down and just eats up space. The div that contains "Proposal Details" in particular - it just wastes space"
2. the spacing between that proposal details div and the content div below it also eats up space
3. the left and right margins eat up space that should be used for content (this one may be fixed with the fixed margins discussed above).
4. the right div that has the About Politeia info really needs to go away - it just wastes space
that div has some utility and doesn't look so out of place on the landing page that lists proposals
on the proposal details page, it is a total waste, imo.
5. I think the font size could come down a bit without causing legibility problems
6. The other thing that stands out to me is the lack of a strong visual indicator between the entries to clearly delineate them (e.g. a drop shadow like the old one has is enough).

What are your thoughts about them?

**Comment by MariaPleshkova** [comment]
1,2. I don't fully understand what was meant by proposal details and proposal content divs, so can't quite get what spacings are not ok.
Imho I wouldn't say that the size of the header is too large, when there are some empty space a page looks clear, not messy and helps focuse on needed information.

3. Regarding left/right margins. As I mentioned above, it's better leave only 1 card in a row, so it will be useless to make margins smaller, because the only thing it's gonna change - there will be more horizontal space for every card, but we don't need to stretch them more than they are now. Not so much info there.

Regarding 4 - I partly agree. But there can be more divs for logged in users:
![image](https://user-images.githubusercontent.com/8841018/65601784-63e71100-dfab-11e9-9ca7-c0618d95067d.png)
And in this case we will have to add About Pi somewhere anyway + there will be more emty space thus we will have to stretch cards to take it (again) or add another info instead of these divs.

5. To be honest, I don't think so

6. Hm. It can make sense. Need to think about it

**Comment by tiagoalvesdulce** [comment]
@MariaPleshkova The red rectangle is the "Proposal Details" div and the green one is the "Proposal Content" div. Their argument is that the "Proposal Details" div is just wasting some vertical space.

<img width="1123" alt="ppslddtls" src="https://user-images.githubusercontent.com/13955303/65619472-95091680-df96-11e9-8a6b-2fe6d0d4bde9.png">

If we remove it, we move the "Proposal Content" div up:

<img width="1116" alt="ppsldetailscorrect1" src="https://user-images.githubusercontent.com/13955303/65619513-a94d1380-df96-11e9-9115-55aaa281d763.png">

If we go ahead and remove the "About Politeia" div on this page, another highly requested layout change by the users on the matrix channel, we have this result:

<img width="1126" alt="ppsldetailscorrect2" src="https://user-images.githubusercontent.com/13955303/65619873-414afd00-df97-11e9-9dc3-9ee9fb4ed2e7.png">

What do you think? Personally, I think that removing the "About Politeia" div is a must for this page and I'm not sure about the "Proposal Details" div.

**Comment by davecgh** [comment]
I'm not too picky on the specifics about the "Proposal Details" and "About Politeia" divs personally.  My main concern is about the most important part of it all -- the actual content.  I would *much* rather have the individual proposal content cards "wasting" space by stretching the entire width of the display than being scrunched up the middle of the screen.  I really can't overstate how horrible that "scrunched up in the middle" design pattern is.  Unfortunately, I see it popping up more and more these days, likely because all of the focus is being put on mobile.

The latest proposed design layout seems quite reasonable to me.  I would also be perfectly happy with the [updates suggested by Maris above](https://github.com/decred/politeiagui/issues/1425#issuecomment-534004010).

**Comment by MariaPleshkova** [comment]
@tiagoalvesdulce yeah, agree, it can make sense for this page. I like what you suggested. The only thing I would leave "Go back" link. And thus we can leave "New proposal" button, because there will be an empty space there anyway.

Like this:
![image](https://user-images.githubusercontent.com/8841018/65677212-e1695a80-e059-11e9-8f97-8b18e7b598e5.png)

![image](https://user-images.githubusercontent.com/8841018/65677268-f80fb180-e059-11e9-8da7-7d82997e00f3.png)

**Comment by tiagoalvesdulce** [comment]
Yeah, looks pretty good!

**Comment by xaur** [comment]
I [complained](https://github.com/decred/politeiagui/issues/843) about sidebar a year ago. Glad it's fixed!
