### ISSUE TITLE
Explore using pandao md editor

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#1474]
@marcopeereboom ran across the pandao open source markdown editor and wanted to explore whether it would make sense to incorporate it into politeiagui in the future.  It appears to be a nice editor that is more feature rich than our current markdown editor.

https://pandao.github.io/editor.md/en.html

This issue is just meant to be a discussion on the merits of possibly switching out editors.  This is not a high priority at the moment so don't allow this to detract from the redesign effort.

**Comment by victorgcramos** [comment]
Hey @lukebp I'd like to give my thoughts on this one! I've been working with our current markdown renderer (not the editor itself), and I think I can contribute to this discussion.

After taking a quick look at the docs (most were google translated because it is written in Chinese), I realized that the markdown parser to HTML might be a good alternative for our markdown parsing because it allows custom renderers, so I guess we can use the features that we have today (XSS filters, external link redirecting modal, etc).

We may also face some issues due to the community support (which is also in Chinese), and I could barely get information from their GitHub discussions regarding the usage with React.

Now I'm working on the Diff component for markdown files, and this parser is a critical part of the diff process. The position of the elements and the text structure both depend directly on how this parser does its job, so it sounds like a good alternative for our current [react-markdown](https://github.com/rexxars/react-markdown). We can use **Pandao's editor.md** markdown to HTML parser along with the [html-to-react](https://github.com/aknuds1/html-to-react) lib... (just brainstorming).

My opinion:

#### Pros:
- Awesome responsiveness
- Great WYSIWYG editor
- LaTeX support (👏 👏 )
- Emoji support

#### Cons:
- Chinese language on docs and community can cause unnecessary overhead
- I did not found any react working example
- We would have to rewrite our XSS filters and other custom renderers for our markdown, especially mentioning the Diff between 2 versions.

**Comment by fernandoabolafio** [comment]
I think depending on which features we actually need we should consider first improving our current editor instead of replacing it with another one. @lukebp could you list what features you're seeing as the most valuable on it that could be immediately integrated? (For example, images among the text are nice but we don't have the backend support for that).
This editor is not a React component so I imagine that we would need to create some sort of React wrapper abstracting it's API to a more concise version that attends our needs. 
It sounds like a work of reasonable complexity but I am open to this possibility as long it can truly add valuable features to the editor and not only flourish the UI.

**Comment by victorgcramos** [comment]
My pleasure, @lukebp. What was the motivation for this idea? Are there any concerns regarding the actual markdown editor?

Thanks!

**Comment by tiagoalvesdulce** [comment]
Closing this issue since we agree to focus on improving our own editor.
