### ISSUE TITLE
Consider replacing yup for forms validation due violation of CSP rule

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1494]
[One of the deps](https://github.com/jquense/expr) used by the package "yup" has a [known conflict](https://github.com/jquense/expr/issues/1) with the CSP rule for dropping "unsafe-eval".  This issue doesn't seem to be in the Yup's roadmap of fixes so we may want to drop this lib and use another one instead.

**Comment by degeri** [comment]
Also need to look into and remove all inline styles https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$157106117612559bJRyz:decred.org?via=decred.org&via=matrix.org&via=zettaport.com

**Comment by amassarwi** [comment]
Would like to consider the alternatives with you guys and implement other library and maybe include the inline styles as well

**Comment by dajohi** [comment]
i'll vote for https://hapi.dev/family/joi/

**Comment by amassarwi** [comment]
@dajohi @hapi/joi looks pretty good to me as well, apparently yup was a try to implement lighter version of it.

**Comment by amassarwi** [comment]
I did small research to find out if there are other alternatives which are lighter than `@hapi/joi` and could also be easily integrated with `Formik` - our forms lib.

Many resources suggest `yup` of course because of the built-in integration within `Formik`, but found an [article](https://itnext.io/simple-react-form-validation-with-formik-yup-and-or-spected-206ebe9e7dcc) which suggesting [Spected](https://github.com/25th-floor/spected) as an alternative, it has pretty **declarative** api & it's **lightweight** and it may fit better to our needs - we won't be validation huge and complex forms.

**Comment by fernandoabolafio** [comment]
I took a look at Spected and it's not so active as joi (last commit was on may). Joi is about 10x heavier (100kb) minified than Spected, however, minified it is only 6kb heavier than Yup. Hence, by being constantly updated, more robust and not a huge difference in size by Yup, I vote for Joi too.

**Comment by tiagoalvesdulce** [comment]
+1 for `@hapi/joi`

**Comment by amassarwi** [comment]
> I took a look at Spected and it's not so active as joi (last commit was on may). Joi is about 10x heavier (100kb) minified than Spected, however, gzpied and minified it is only 6kb heavier than Yup. Hence, by being constantly updated, more robust and not a huge difference in size by Yup, I vote for Joi too.

With that said, +1 for `@hapi/joi` from me side as well.

**Comment by fernandoabolafio** [comment]
Should be tracked on https://github.com/decred/politeiagui/issues/1503.
