### ISSUE TITLE
Search for votes modal fetching votes before 

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#1561]
We are fetching the proposal votes before doing a search, creating a bad UX:

![searchvotes](https://user-images.githubusercontent.com/13955303/68209514-4cd80d80-ffb2-11e9-9e47-1b56439af229.gif)

In my opinion, we should fetch the proposal votes after the first search and save it on the state to allow multiple searches without fetching the votes again.

**Comment by amassarwi** [comment]
Would like to work on it

**Comment by fernandoabolafio** [comment]
The votes are fetched before because the API endpoint returns all tickets at once. So, if in one hand you have to wait a bit for the votes fetching, in the other the search is instataneously.
Also, the vote  response payload can be quite large, that's why we don't keep it cached and instead we fetch it locally in the modal as needed.
Tbh I am fine with this as it is. Feel free to move this forward if you think it is necessary, up to you.

**Comment by tiagoalvesdulce** [comment]
I know the request takes some time to be done. We can even start doing it in the background when the modal is opened but the feedback for the user should be faster. It's weird to open a modal and wait almost 5 seconds to see something, but when doing a search the user expects some delay.

About caching the data, I think it's a good idea exactly because it's a large amount of data. We can provide a better experience to the user by doing that without major performance issues. In general, I would strongly suggest profiling performance problems before being wary of them. Often what might seem like a problem is actually not one. I think the extra space used to store on state will be beneficial due to the time it can reduce. Also, if we do it right and keep this state in its own branch (own reducer), we shouldn't touch it when not searching votes.

IMO we should give it a try. But we can wait to see if people start complaining about this more often.
