### ISSUE TITLE
Duplicated comments 

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#1601]
In this thread, the "plusbit" comment was replicated 3 times: https://proposals.decred.org/proposals/e559188b0febcab29c49c1f7dd5c66645e31be00894a150ef7d0b8ceb6486605/comments/4. 
From the [raw data](https://github.com/decred-proposals/mainnet/blob/master/e559188b0febcab29c49c1f7dd5c66645e31be00894a150ef7d0b8ceb6486605/1/plugins/decred/comments.journal
) we can notice a few things:
- 2 out of the 3 comments have exactly the same body text, thus the same signature.
- 1 out of the 3 comments is slightly different because it has a blank space at the end of the body text.

It is likely that multiple requests are being fired from the GUI when submitting a new comment but I couldn't reproduce this behavior so far. 

One thing that is clear we need to do is to trim comments to make sure it doesn't make to the API with blank spaces at the end of the text. This should be addressed by: https://github.com/decred/politeiagui/pull/1600.

**Comment by lukebp** [comment]
Another instance of this happening.

https://matrix.to/#/!VFRvyndKpzcLrVslQD:decred.org/$157581204658910QrbZF:decred.org?via=decred.org&via=matrix.org&via=zettaport.com

**Comment by lukebp** [comment]
@xaur posted a detailed bug report here with more details.

https://github.com/decred/politeia/issues/931#issuecomment-562850323

cc: @amassarwi

**Comment by xaur** [comment]
Just had a situation very similar to#931: long "loading" after pressing "Add comment" that ended with "Server error". I figured that my comment got stuck somewhere and went ahead to post other comments. After several minutes (like 10?) my first comment [appeared](https://proposals.decred.org/proposals/012b4e335f25704e28ef196d650316dca421f730225d39e37b31b3c646eb8497/comments/81).

**Comment by lukebp** [comment]
hmm so it sounds like the politeia backend was busy doing something, your request timed out, and then the backend added the comment successfully after the backend finished doing whatever it was doing.  I'd have to look into it more, but there really only a couple of things that could hold politeia up like that.

Looking at the timestamp of the comment `1579320099`, it was added right at the start of the hour (4:01AM UTC).  This makes me think that its related to anchoring (i.e. timestamping) the data to the decred blockchain.  We anchor the data at minute 58 of every hour.  That process includes moving around a bunch of data into the git repos and then interacting with the dcrtime server.  The politeiad server is going to be locked up during a good part of this, which is likely what was causing your request to hang and then time out.

If this is indeed what is happening it will resolve itself when we switch to a tlog backend because we won't have all the git interactions during the anchoring process, which is likely what is keeping politeiad locked down.

**Comment by lukebp** [comment]
The fact that we have three ongoing proposal votes would also exacerbate this problem.  The votes being trickled in would cause a backlog of work during the anchoring process and it might take politeiad a minute or two to catch back up after the anchoring process is complete.

**Comment by amassarwi** [comment]
After looking into another duplicated comment [case](https://proposals.decred.org/proposals/95cfb73254a032b2c199c37bb499d6f172d044b1f38016279c5bbca6572251f0l), which happend again around backend anchoring event, @lukebp 's comment explaining what causes the issue.
 
> Looking at the timestamp of the comment 1579320099, it was added right at the start of the hour (4:01AM UTC). This makes me think that its related to anchoring (i.e. timestamping) the data to the decred blockchain. We anchor the data at minute 58 of every hour. That process includes moving around a bunch of data into the git repos and then interacting with the dcrtime server. The politeiad server is going to be locked up during a good part of this, which is likely what was causing your request to hang and then time out.

**With that said, closing the issue - will be handled on the BE side.**

**Comment by xaur** [comment]
> With that said, closing the issue - will be handled on the BE side.

@amassarwi please link to the corresponding BE issue.

**Comment by amassarwi** [comment]
@xaur sure, https://github.com/decred/politeia/issues/1112 is the new issue on the BE side.
