### ISSUE TITLE
Improve useAPIAction hook to memoize arguments

### ISSUE THREAD

**Issue by victorgcramos** [decred/politeiagui#1764]
Every time we want to use the `useAPIAction` passing arguments to it, we must memoize the request's parameter values, like:

https://github.com/decred/politeiagui/blob/7f95223734fa8172955dab23eb57796d56e2a2fb/src/hooks/api/useExchangeRate.js#L27-L32

and

https://github.com/decred/politeiagui/blob/7f95223734fa8172955dab23eb57796d56e2a2fb/src/containers/Invoice/Detail/hooks.js#L14-L19

...

The idea is to avoid this behaviour, and memoize those values inside the `useAPIAction` hook.

**Comment by victorgcramos** [comment]
Thanks to @tiagoalvesdulce's observation on #1751.

**Comment by fernandoabolafio** [comment]
Unfortunately, there isn't an optimal way of doing this because we will always be specifying an object as a parameter that will always fail in the shallow comparison. The only way it would work is could work is if the parameter is a non-object variable (e.g string, number, boolean). That said, I think what we can do to avoid a mistake is to discard the use of `useAPIAction` and in every component/hook we want an action we will call the dispatch and create the callback (if needed):

```jsx
const dispatch = useDispatch();

// either do
dispatch(someAction());

// or
const callback = useCallback(() => dispatch(someAction(params)), [params])

```

In terms of verbosity I think both approaches are equal but the one I presented will prevent mistakes of not memorizing the parameters thus leading to unwanted re-renders.

**Comment by tiagoalvesdulce** [comment]
Your approach is OK. My concern about the current approach is that it's not obvious for newcomers that they have to memoize the `useAPIAction()` params before passing them to the hook in order to prevent infinite loops. We can either use your approach or create our custom memoization utility with deep comparison and make it clear to not use it with deeply nested objects.

**Comment by fernandoabolafio** [comment]
@tiagoalvesdulce my fear is about the 'make clear' part of it. I would rather use an approach that prevents errors by itself. If we explicitly use the dispatch to fire actions we mitigate those risks. It's also weird that we need to enforce the memoization  of function arguments. 
Can we enforce what has to be the function argument for the function (like typescript) using something else like flow or just plain js? I am just thinking that would be fine to use `useAPIAction` as long as the parameters are not objects.

**Comment by fernandoabolafio** [comment]
I was taking a look at this discussion: https://github.com/facebook/react/issues/14476 and Dan Abramov actually suggests something similar to what we're doing:

## Option 2: Embrace dynamic values
Another option is the opposite. Embrace that values are always dynamic, and ask the API consumer to memoize them.

```js
function MyComponent() {
  const config = useMemo(() => ({
    foo: 42,
  }, []); // Memoized
  const data = useFetch(url, config);
}
````
This might seem like it's convoluted. However for low-level Hooks you probably will create higher-level wrappers anyway. So those can be responsible for correct memoization.

```js
// ./myUseFetch.js
import {useContext} from 'react';
import useFetch from 'some-library';
import AuthContext from './auth-context';

export function useFetchWithAuth(url) {
  const authToken = useContext(AuthContext);
  const config = useMemo(() => ({
    foo: 42,
    auth: authToken
  }), [authToken]); // Only changes the config if authToken changes
  return useFetch(url, config);
}

// ./MyComponent.js
function MyComponent() {
  const data = useFethWithAuth('someurl.com'); // No config
}
```
Then effectively the users don't need to configure anything at the call site — or you can expose limited supported options as specific arguments. That's probably a better API than an arbitrarily deep "options" object anyway.

**Comment by tiagoalvesdulce** [comment]
Nice discussion but I keep my argument that it's not clear for people that are going through the code for the first time that they **have** to memoize the arguments of a hook otherwise it will trigger an infinite loop. His argument is that higher-level wrappers will be created for low-level hooks. If we create a wrapper around the `useAPIAction` hook, memoize the params there, explain why we are doing the memoization with comments and refactor our code to use only the wrapper I will be pleased.
