### ISSUE TITLE
Crash when logging out from account page

### ISSUE THREAD

**Issue by thi4go** [decred/politeiagui#1914]
We are getting a crash when a user tries to logout from his user account page. Aparently pgui tries to hit a verify payment route after the logout, a route that requires the user to be logged in, thus resulting in the crash. See below:

![logout_bug](https://user-images.githubusercontent.com/2729122/81582967-10350680-9387-11ea-9e94-6950f21b043c.gif)

**Comment by tiagoalvesdulce** [comment]
This isn't a crash. You are seeing the unhandled rejection error because we don't handle the error of `verifypayment` in the login route. We can wrap the entire app with an `ErrorBoundary` to swallow errors like this one but you are seeing this message because you are in `dev`. It *will not* happen on `prod.`

**Comment by thi4go** [comment]
Oh I see, different error scope then. Thanks for the explanation mate @tiagoalvesdulce. I'll close this issue.

**Comment by tiagoalvesdulce** [comment]
Np, should be improved anyway when we have a better way to verify user payments, with WebSockets maybe :)
