### ISSUE TITLE
[cms] Refresh of /admin/invoices causes filters to reset

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1934]
It would be nice if there was a way to retain filters that were set after a refresh of admin/invoices.  Not sure that can be saved through a hard refresh though, but something to fix that would greatly improve QoL for administrators during review.

**Comment by tiagoalvesdulce** [comment]
This is doable. Do we want these filters retained only after a refresh or after the browser is closed as well?

**Comment by alexlyp** [comment]
mmm Browser close would be cool too

**Comment by tiagoalvesdulce** [comment]
Sure, we should save them in the localStorage then.

**Comment by alexlyp** [comment]
Ah that would be great!

**Comment by xaur** [comment]
Just noticed this issue and I'd like to mention a related change.

While using the new same-domain invoice peer review feature during several monthly cycles, I found myself missing new invoices due to filters not being reset between review sessions. To prevent that I requested a change in #2265 and #2296, which were implemented in #2285 and #2298. Notably, it is the opposite change that was requested in this issue.

My issue was concerning `/invoices` and not `/admin/invoices` as discussed in this issue, and I hope admin pages were not affected. But if admins have encountered the same problem as I did, the same change can be considered for admin pages.
