### ISSUE TITLE
Difficult to add proposals to RFP

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#2139]
I added a proposal to the RFP and I had to find the full length proposal token for the RFP I was submitting on, I don't know if this is used much on proposals site any more but I got it from the dcrdata proposals page. If it could be a drop-down of currently open RFP proposals that would be much easier UX.

**Comment by lukebp** [comment]
This would require backend changes first.

**Comment by lukebp** [comment]
For future reference, you can find the token on the proposal page.
![Screenshot from 2020-09-24 08-04-33](https://user-images.githubusercontent.com/9039877/94148841-c2540300-fe3c-11ea-8dac-1c9ec7fd847d.png)

**Comment by lukebp** [comment]
One of the limitations the new tlog backend has is the inability to query random pieces of data like you can with a normal database.  Adding nice to have gui features, like populating a RFP dropdown menue, becomes far more difficult.  In order to add these additional queries there has to be a substancial ROI to UX, which this wouldn't qualify for.

The way I would suggest improving the UX here is by adding an information icon, like we do with the deadline, that tells the user they can find the RFP token on the RFP proposal page.

![Screenshot from 2020-09-24 08-07-46](https://user-images.githubusercontent.com/9039877/94149803-f7ad2080-fe3d-11ea-8ee4-06bbb142ef9d.png)

**Comment by lukebp** [comment]
@victorgcramos this creates edge cases where the RFP isn't cached and therefor doesn't show up in the dropdown list.  I don't want that added to pi.  I'd rather keep it simple and have the user paste the proposal token manually.

**Comment by lukebp** [comment]
@victorgcramos this creates edge cases where the RFP isn't cached and therefor doesn't show up in the dropdown list.  I don't want that added to pi.  I'd rather keep it simple and have the user paste the proposal token manually.

**Comment by victorgcramos** [comment]
sounds fair, @lukebp
