### ISSUE TITLE
[proposals2] Start vote modal wrong testnet values.

### ISSUE THREAD

**Issue by amassarwi** [decred/politeiagui#2321]
![image](https://user-images.githubusercontent.com/10324528/113624023-cd97af00-9667-11eb-9cf8-9a639fc5fd5d.png)

**Comment by lukebp** [comment]
This is because the gui is using the wrong policy reply for the min vote durations.  Its using the policy reply from the `www` API when it should be using the policy reply from the `ticketvote` API.  The `www` policy reply fields that relate to proposals, comments, and ticket votes have been deprecated.

I thought this was already fixed, but I guess not.

**Comment by amassarwi** [comment]
I guess it just debugging left over, gui should already use the BE value when providing the 3 possible duration values.

**Comment by amassarwi** [comment]
Could be just debugging/test left over change.

**Comment by thi4go** [comment]
On this
