### ISSUE TITLE
Remove references to proposals/invoices from the code

### ISSUE THREAD

**Issue by tiagoalvesdulce** [decred/politeiagui#2335]
We should use a more general term like `records`

**Comment by victorgcramos** [comment]
Hmm, since we are getting rid of proposals/invoices naming, we should also reorganize our state tree to match the new architecture. Now, the only thing that differs one record from another is its `metadata`, so I don't think it makes sense to store both invoices and proposals on the store. What do you guys think? @tiagoalvesdulce @thi4go

**Comment by amassarwi** [comment]
@victorgcramos 
Makes total sense.

**Comment by victorgcramos** [comment]
@amassarwi I had a conversation with tiago earlier and we thought it would be better to focus on e2e testing for both cms and gui before jumping into the state changes. What do you think @amassarwi?

**Comment by amassarwi** [comment]
Also makes sense mates

**Comment by lukebp** [comment]
This is a very broad issue.  I think we can accomplish this on an ongoing basis as new work gets added to politeiagui.  If you feel this is still relevant, you can open a new issue that contains actionable items.
