### ISSUE TITLE
View raw markdown

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2415]
If somebody wants to view the raw markdown of a proposal there's currently no easy way to do this.  They must download the proposal bundle and then decode the base64 manually in order to view it.  It would be nice to have the option of viewing the raw markdown in the browser, similar to how github allows you view raw markdown.

Does the markdown rendering library that we use allow for this?
How difficult would this be to implement?

cc: @tiagoalvesdulce

**Comment by tiagoalvesdulce** [comment]
It should be pretty straight forward. We don't need the markdown renderer to implement this because we can just print the raw string on the page. The only thing that will be a pain is to deal with images because we use base64 so the raw string is too big for a good UX. My suggestion is that we parse and print images but keep everything else raw. What do you think?

**Comment by amassarwi** [comment]
We could also do something similar to github with images, show some kind of `<img ....` tag or something.

**Comment by lukebp** [comment]
Not sure I follow.  Are you talking about inline images?  If so, wouldn't we just print the markdown that references the image?

If you're not talking about images then I don't think this issue would apply.  This would just be for `.md` files.

**Comment by tiagoalvesdulce** [comment]
hmm, yeah, we can just print the markdown that references the image (image digest).

**Comment by xaur** [comment]
I was missing this very feature recently. Access to raw Markdown allows to save it locally and diff proposal revisions with the tool of choice. Thanks for submitting and implementing.
