### ISSUE TITLE
Comment vote highlighting

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2517]
When you upvote/downvote a comment, the icon does not become highlighted until a succesful response is received from the server.  This creates the appearance of lag, especially when there is larger than normal latency in the server reply.

The way this should work is that the upvote/downvote icon should become highlighted on click.  If the request fails for some reason then it should be removed.

Failed comment votes are the edge case and we should design the UX to reflect that.

**Comment by victorgcramos** [comment]
On it!

**Comment by xaur** [comment]
@lukebp for background, I requested to remove the speculative highlighting in #1792 (Feb 2020) and it was implemented in #1823 (Mar 2020). The motivation was the following two issues:

1\. It lies to the user that the action happened before it did.

It is not a (big) problem by itself, but it becomes a problem if the action fails. I encountered a real case when I upvoted a bunch of comments and closed the tab thinking the upvotes were cast, and later discovered (by accident) they were not cast.

2\. It hides performance issues. Previous behavior (before #2520) didn't create an appearance, it showed what it is - a slow response.

Personally, I prefer when software does not try to make things look fast when they are not fast. As a vivid example, you might remember the WiFi connection dialog in Windows 7. Once you press Connect it shows a progress animation that it is connecting, and hides the entire dialog after a few seconds to appear "fast". But if you click the WiFi icon in the system tray, it is still connecting.

The reason I bring it up is because I would like to avoid bugs where user data is silently lost without even making the user aware of it, even if it is as small as a few comment upvotes.

If you really want to have speculative success animations, I suggest to add loud and clear error popups or "toasts" like "Failed to case comment vote. Please try again or report the issue" so that the users at least know it didn't work (and ideally notify the admins so they know too and can investigate).

**Comment by xaur** [comment]
P.S. just noticed the gif in #2520 and it does have an error notification if upvote failed. Error text and positioning can be improved but at least it is not silent.
