### ISSUE TITLE
Raw Markdown page fetching 2.5 MB

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2533]
When I open a raw markdown page [like this](https://proposals.decred.org/record/e2d7b7d/raw), it shows a basic text page with no UI, but it makes 12 requests and the last one pulls a 2.6 MB JSON.

This is unexpected because I see no heavy images or anything like that in that proposal.

**Comment by lukebp** [comment]
The 2.6 MB request that you're seeing is a bug that will be fixed in the next deployment (#2534).

The rest of the requests are a result of how the markdown page was implemented in the gui.  It's part of the proposal details hierarchy and those requests are the same requests that fire when you load the proposal details page.  It could be pulled out, but this is not a quick change and it's not worth it to make that investment since this will be removed in the future.  This was the quick and dirty way to implement it.  The proper way to do it is to serve the markdown directly from the backend.
