### ISSUE TITLE
Improve search engine result snippet

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#2600]
When you search `decred politeia` in a search engine, the following result is displayed.

![image](https://user-images.githubusercontent.com/9039877/134509654-211ffa83-78a0-4785-99af-816e9670a994.png)

We need to fix these results.

https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets

**Comment by victorgcramos** [comment]
On other search engines rather than duckduckgo display the following:

Google:
<img width="600" alt="Screen Shot 2021-09-23 at 6 40 03 PM" src="https://user-images.githubusercontent.com/22639213/134587835-5a317dc4-96d3-4d8d-9728-d2c01a0c2696.png">

Bing:
<img width="638" alt="Screen Shot 2021-09-23 at 6 41 07 PM" src="https://user-images.githubusercontent.com/22639213/134587953-e7374808-3293-4242-ad09-04b57fe72a20.png">

Yahoo:
<img width="432" alt="Screen Shot 2021-09-23 at 6 42 03 PM" src="https://user-images.githubusercontent.com/22639213/134588038-7b633343-65cd-4537-a2bc-fe04cadd1963.png">

AOL:
<img width="582" alt="Screen Shot 2021-09-23 at 6 43 15 PM" src="https://user-images.githubusercontent.com/22639213/134588157-95b4cb9a-9879-4883-a5dc-9cdc7066e4f1.png">

**Comment by victorgcramos** [comment]
On it!

**Comment by lukebp** [comment]
Interesting.  Good idea to check all of them.
