### ISSUE TITLE
Typing a comment is slow

### ISSUE THREAD

**Issue by sndurkin** [decred/politeiagui#432]
When typing in the comment box on a proposal detail page, it seems to have a pretty slow response. This might get worse by having more comments on the page.

**Comment by tiagoalvesdulce** [comment]
@fernandoabolafio any clue?

**Comment by sndurkin** [comment]
I did some initial investigation, and it definitely seems to be the `onChange` -> `value` flow (the `@@redux-form/CHANGE` action is dispatched), and the problem gets worse as you have more comments on the page. I don't know anything about redux form but it looks like there is an excessive number of `ReduxForm`s on the page, at least one for every comment:

![image](https://user-images.githubusercontent.com/1452379/42661567-96c6c4f8-85fc-11e8-8c98-4154b9d95bca.png)

**Comment by fernandoabolafio** [comment]
I think the problem is that we are mapping the same prop value (the form value) to all forms. Thus, the onChange event causes all forms to re-render. So, as the number of comments increases, the effort to render all of the components increases as well. 
We need a way to map separately the input values to every single form. So they don't share a common state of the input value.
