### ISSUE TITLE
Prevent unecessary re-renders of the entire comments list

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#464]
All row components from the comments list are responding (re-rendering) to those events:
- **Submitting a new comment:** when the API request succeeds and the new comment is added to the comments list, causing the entire list to re-render.
- **Voting up/down on a comment:** when the API request succeeds and the vote result is merged to the comments list, causing the entire list to re-render

Only the affected list items should re-rendered on those situations described above.

**Comment by camus-code** [comment]
Been toying with this issue the last few days @fernandoabolafio

I've been testing it with 100+ comments and I noticed the performance really starts to suffer once that many comments are being re-rendered. I'm fairly certain the culprit lies within `ProposalDetail.js` or its related helper. 

If I'm not mistaken, `handleUpdateOfComments` seems to be at the root of it, as it's being called quite a few times throughout the lifecycle of this component. 

Hopefully will have a fix up by the weekend.

**Comment by fernandoabolafio** [comment]
Hey @camus-code. As far as I know there isn't an easy fix for this issue. 
An approach that comes to my mind for this situation is to avoid passing the comments props from the list parent to it's child. 
For a flat list scenario it would look like:

```
const CommentsList = ({ listLength }) => {
  const comments = []
  for(let i=0; i < listLength; i++) {
    comments.push(<Comment idx={i} />)
  }
  return <ul>{comments}</ul>
 }

const Comment = ({ getCommentPropsByIndex, idx }) => {
 const { comment } = getCommentPropsByIndex (idx)
 return <li>{comment}</li>
}

```
While this example is theoretical because our case handles a nested list and you have the sorting logic; it gives you the idea, the comment items access their props through a selector so it will only react to to its own prop changes instead of reacting to every list change.

**Comment by marcopeereboom** [comment]
This was fixed.
