### ISSUE TITLE
registration paywall: improve notifications and flow

### ISSUE THREAD

**Issue by behindtext** [decred/politeiagui#585]
the process for creating a new account works, but the paywall part does not flow well. in particular, you sign in for the first time and are presented with a red error notification modal that says further action is required. you follow a link to your profile page, where there is another red error modal that cues you to pay to complete your account registration.

this process needs to be more natural and not be presented to the user as an error modal or div. the color red should not be used since this is typically associated with errors, not further steps in a standard process.

**Comment by camus-code** [comment]
Thought the same thing. not working on this ATM but I think changing the modal type from "error" to "info" would clean things up a ton. 

Thinking about how to streamline it further before I start working on this issue

**Comment by fernandoabolafio** [comment]
I like your idea of changing the modal type from "error" to "info" @camus-code . 
I will list that and also other thoughts I had on how to improve it:
- 1 Change the modal type from "error" to "info"
- Change the modal Title from "Action needed" to "Complete your registration"
- Present the alert within the sidebar menu instead of the Header Modal, which is a bit annoying since it keeps overlapping other contents.
- Insert the paywall widget inside a modal which can be accessed from anywhere so the user doesn't have to be redirected to the account page.
- Create a link on the last step of the On boarding modal instructing the user to complete his registration.

**Comment by camus-code** [comment]
awesome suggestions @fernandoabolafio .

Like I said, the only other idea I have for now would be to make the modal message a little more specific so that the user knows the paywall is the part which is preventing them from completing registration.

**Comment by fernandoabolafio** [comment]
Regarding this [doc](https://docs.google.com/document/d/1NMlJGWMZC88JqNRcGMzdM4uTIcq84Cis2Fa4YcPoeXU/edit?usp=sharing) sent by 
@s_ben on slack, here are my comments:

> The info box on the signup page is good. However, would make a few copy changes to make things more clear and concise.
I agree that this text is a bit too long. Any other models for us to test would be nice.
>also, are we not verifying email via emailed registration link anymore?
We are still emailing verification links. This won’t happen in case you are running politeia on your localhost. If you aren’t receiving the link on test-proposals.decred.org or on proposals.decred.org please confirm that because it can be a bug.

>Pretending to be a user, I was a bit confused. Especially since there is no ‘Next’ (or other) button at the bottom that takes me to the next screen. The buttons at the bottom only scroll through the tabs, which indicates that you must go through the tabs to do signup (which isn’t technically true, I can X out at any time and get the same behavior as if I read every tab)


When the user sees this screen he has already completed the sign up and logged in so I don’t see a reason why it can be seen as a required part of the “signup process”. This is a on boarding information which the user can choose to read or dismiss, thus the “X” available at the top. We could also remove the X and force the user to go trough every tab before closing it (I don’t really like it).

>“Am I exiting this flow before my registration is complete? Am I going to have to do this again?“). I would suggest removing this screen altogether, and putting a link to this on the sidebar, or as an (optional) last screen the user sees once they’ve finished the registration process (which is quite long already). Goal is to reduce friction. 

IMO on boarding steps should be seen at the very first contact of the user with Politeia. However, If it was confusing for you it can also be for other users, so we could add a subtitle or a short text above the tabs indicating that this is a optional read and doesn’t affect their registration.  Another improvement is to create a button “ok, got it” on the last screen which also closes the modal and may remove this “fear” from the user when closing the modal.
Also,  there is a link for opening this modal on the sidebar, it is the “Read More” link (I think we can use a better wording for that).

> “You have successfully created a Politeia account! 
You can now browse the website and view existing proposals […]
Right now isn’t technically possible to apply the paywall on this screen since the paywall data requires the user to be logged in, so it would requires some changes on the backend in order to fetch paywall information trough some other endpoint which doesn’t require authentication (maybe returning this data alongside with the confirmation of the email verification?)

> I would suggest turning this modal into an (optional) screen, which the user sees if they click the ‘Complete Registration’ button on the previous screen. In general, something like this feels more like a screen than a modal anyway, which seems better for smaller messages (errors, warning, tips). 

I like the idea of removing the modal alert and adding a more “optional link” somewhere else. Im actually working towards this idea on my current PR.

**Comment by tiagoalvesdulce** [comment]
The suggestions on this thread are great. I'll just add some minor thoughts.

> The info box on the signup page is good. However, would make a few copy changes to make things more clear and concise.

I definitely agree with this. Actually, I think the first paragraph of that infobox can be removed.

> When the user sees this screen he has already completed the sign up and logged in so I don’t see a reason why it can be seen as a required part of the “signup process”. This is a on boarding information which the user can choose to read or dismiss, thus the “X” available at the top. We could also remove the X and force the user to go trough every tab before closing it (I don’t really like it).

I think that we can open a modal with a "Welcome! Not sure what Politeia is? Want to read more about it?" message (or something like this) and two options "Sure, show me more" and "No, I know how Politeia works". And then open the onboard modal or not.

> Also, there is a link for opening this modal on the sidebar, it is the “Read More” link (I think we can use a better wording for that).

I agree a better wording would be good. Maybe "Open onboard modal to read more"

> "You have successfully created a Politeia account!"

> Right now isn’t technically possible to apply the paywall on this screen since the paywall data requires the user to be logged in.

I think that here we can allow the user to login (we have a login modal that should be useful!) and redirect the user to a place to pay the paywall if the login is successful. Other suggestion would be to split the `Account` screen into `Identity`, `Paywall`, `Proposal Credits` and `Account Info` so we could redirect the user directly to the `Paywall` screen. If the user doesn't login right after the Signup, I do think our "pay the paywall" modal message can be improved to be more friendly.

**Comment by camus-code** [comment]
Agree with pretty much everything above. Adding just a few small comments where I see fit

> When the user sees this screen he has already completed the sign up and logged in so I don’t see a reason why it can be seen as a required part of the “signup process”. This is a on boarding information which the user can choose to read or dismiss, thus the “X” available at the top. We could also remove the X and force the user to go trough every tab before closing it (I don’t really like it).

>> I think that we can open a modal with a "Welcome! Not sure what Politeia is? Want to read more about it?" message (or something like this) and two options "Sure, show me more" and "No, I know how Politeia works". And then open the onboard modal or not.

Really like this idea of incorporating another modal before the onboard modal. Gives users flexibility + they know exactly what they'll be looking at rather than it just popping up. This modal should probably have a `finish` button on the last screen that closes it out to make it flow a bit better.

> I think that here we can allow the user to login (we have a login modal that should be useful!) and redirect the user to a place to pay the paywall if the login is successful. Other suggestion would be to split the `Account` screen into `Identity`, `Paywall`, `Proposal Credits` and `Account Info` so we could redirect the user directly to the `Paywall` screen. If the user doesn't login right after the Signup, I do think our "pay the paywall" modal message can be improved to be more friendly.

Agree with all of this as well. If we wanted to keep `Account` on one screen, though, I'd suggest to make the paywall modal a pop-up (similar to the on boarding one) so that the user knows what they have to do before proceeding. If we go for this solution, we could also replace the generic `Error` modal on the home screen with the `Paywall` one.

**Comment by tiagoalvesdulce** [comment]
I splited the suggestions on this thread that were not addressed by @fernandoabolafio on #605 into two issues (#606 and #607)

**Comment by s-ben** [comment]
Sounds like some good improvements are being made. Going to make a pass at tweaking copy on info box. Will create an Issue, then submit a PR with new text for review (unless you think it would be more efficient to just paste proposed copy here or slack). Could also take a pass at copy in other parts of the GUI, but it sounds like that is a lower priority now, with Pi nearing release! @fernandoabolafio @tiagoalvesdulce @camus-code

**Comment by tiagoalvesdulce** [comment]
There's already an issue for that (https://github.com/decred/politeiagui/issues/608). We can do further discussions there.
