### ISSUE TITLE
[proposal credits] "created_by_dbutil" shouldn't be a link

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#631]
Transactions created by db util must be shown as plain text.

![screen shot 2018-09-26 at 10 47 35 am](https://user-images.githubusercontent.com/14864439/46084397-f32fcd80-c179-11e8-8538-9915e928cb0f.png)

**Comment by derekdkim** [comment]
Can I give this a shot?

**Comment by derekdkim** [comment]
Hi, I narrowed down the problem to Summary.js, where the credit-purchase-tx is being getting an <a> element from DcrdataTxLink. What I don't understand is where something like created_by_dbutil is coming from. I have no experience with React or REST APIs I would appreciate it if you can give me a hint.

**Comment by sndurkin** [comment]
@derekdkim, "created_by_dbutil" is actually coming from the server. The actual string is generated by https://github.com/decred/politeia/blob/55e6706959765422d01818983777047a5ec18893/politeiawww/cmd/politeiawww_dbutil/politeiawww_dbutil.go#L181 and stored in the database. The only way for the client to differentiate is to check that the string is to maybe check that the string is of the correct length for a transaction id, and only contains numbers and a-f characters.

**Comment by derekdkim** [comment]
Would something like this work?

`
const DcrdataTxLink = ({
  isTestnet,
  txId
}) => {
  const network = isTestnet ? "testnet" : "explorer";
  // Confirm valid transaction by checking for presence of numbers in its ID.
  if (/\d/.test(txId) === true) {
    return (
      <a href={`https://${network}.dcrdata.org/tx/${txId}`} target="_blank" rel="noopener noreferrer">
        {txId}
      </a>
    );
  } else {
    return (
      <p>txId</p>
    );
  }
};
`

I still have trouble grasping everything, but my reasoning was that if the txId of the transaction doesn't contain any numbers (meaning it must be a phrase instead of a randomly generated id), it should return a <p> element instead of <a> to create a plaintext rather than a link. Am I on the right track?

Thanks for your patience.

**Comment by sndurkin** [comment]
Personally, I would ask marco or dhill the best way to identify a txn id string. If they say testing for a number is sufficient then the code you have is fine. Although I would return <span> instead of <p>.

**Comment by camus-code** [comment]
Fixing this big
