### ISSUE TITLE
[user details] Unecessary requests to "height" on switch tabs

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/politeiagui#674]
- Go to user details route `/user/:userid` and open the network console.
 - Switch back and forth the tabs
 
Requests to `https://testnet.dcrdata.org/api/block/best/height` are fired multiple times. It must be fired only once.

**Comment by camus-code** [comment]
I think the request to height can be bundled within the `if(csrf)` statement [](https://github.com/decred/politeiagui/blob/cce6cd2c4465c19583f3e046de2d1e4539d1f31f/src/components/snew/Content.js#L124) since this statement only fires on the page load and not tab switching.

Let me know if there's an issue with this fix @fernandoabolafio
