### ISSUE TITLE
[UI/UX] Unable to get to user page from account page and mismatched info

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#740]
There is information on the user page that is not on the account page, such as whether the email address has been verified, whether the registration fee has been paid, and if so, the transaction used to pay it.

Unfortunately, the user page is also fairly well hidden in that the account page has no link to get there (although it does display your user ID).  As a result, in order to get to the user page, you either need to have to performed some action such as commenting on a proposal in order to get a link to it, or simply have to know that URL and manually put your user ID in there.

A relatively quick change that would at least provide a means to get to the user page from the account page would be to make the displayed user ID on the account page a link to the user page.

However, I think, ultimately, the pages probably need to be combined.

**Comment by sndurkin** [comment]
To implement folding the account page into the user page, here's what I would recommend:

* The "What is an identity?" help section on the account page should go after the "Active Identity" field on the General tab of the user page.
* Similarly, the lost identity text and identity action buttons on the account page should go after the "Active Identity" field. The buttons could maybe be reduced in size a little.
* The "Change Username" and "Change Password" forms on the account page can be hidden behind links on the user page. The username as the top can have a "Change" link next to it which opens a modal with the Change Username form. For password, we could create a dummy field after "Verified email" like "Password: _(never shown)_" which is never populated with the actual password, and then put a "Change" link next to it.
* The "Account" link in the top-right user menu should navigate to the user detail page and specifically show the General tab rather than the Proposals tab. This may require each tab to have a different url, like `/user/<user id>#General`, `/user/<user id>#Proposals`, etc. The General tab isn't shown when visiting other user detail pages (unless you're an admin).
* Eventually it would be nice if the user proposals page was folded into the user detail page too (including draft proposals), but that can be done at a later time.

**Comment by camus-code** [comment]
Thanks for all the recommendations @sndurkin ! I really appreciate it. I'll be working on this ASAP
