### ISSUE TITLE
Local development environment against politeiawww

### ISSUE THREAD

**Issue by NerdsvilleCEO** [decred/politeiagui#743]
When I try to run politeiagui on my local box using yarn with the command in the docs:

```
  yarn && yarn start
```

I notice that I get ERR_EMPTY_RESPONSE in chrome and with curl: (52) Empty reply from server

Related to https://github.com/decred/politeiagui/issues/725

**Comment by tiagoalvesdulce** [comment]
This problem is not caused by the politeiagui setup itself. Some common problems that can cause this error are:

1.  You are not allowing incoming network connections from “politeiawww”.
2. Your firewall or antivirus are blocking the network connections.
3. Your browsing data is causing weird issues.
4. You have improper network or DNS settings.
