### ISSUE TITLE
[Bug] "Resend verification email" not working

### ISSUE THREAD

**Issue by Arriu** [decred/politeiagui#745]
Yesterday I signed up with my intended email address and username, but the verification failed.
I have since figured out what caused the verification to fail, and have created and verified a new account with a new email address. However, the email adress and username i originally used are now stuck. The username shows up as taken when i try to change my verified account to it. I can't use the email adress to do the sign up process again and the "Resend verification email" button does nothing. The only thing I can do is "Reset Password," which does work and after i've clicked the link and chosen a new password,  I'm told "Password reset completed. Your password has been changed. You can now login with your new password." However, when i try to do that, I get "Login error. The provided email address or password was invalid."

**Comment by marcopeereboom** [comment]
We think we have diagnosed and solved most of these issues. We are in the process to get this code ready for mainnet.

The change email part is something we deliberately have been very careful with and a solution to this will be deployed soon as well. My current thinking is that this will be a manual process of sorts.

**Comment by sndurkin** [comment]
@Arriu the reason Resend verification email doesn't do anything is because to prevent email spam, Politeia only sends 1 verification email every 48 hours. This is different for every verification type, which is why you can get a reset password verification email but not another registration verification email. I think to remedy this, we should:

1. Change resend verification to be a new verification type so the user can request 1 more registration email within the 48 hour span.

2. Prevent the user from resetting the password before he has verified his email. This just leads to confusion because he still can't login.

3. Add a new error type for when the user enters his correct email & password but is not yet verified. We need to explain to the user that he needs to verify his email first, and offer the "Resend verification email" link.

**Comment by Arriu** [comment]
Thank you both for your quick responses. I like all the suggestions made by sndurking and the only thing I could add is to explicitly mention to the user that is it one (or two in the case suggestion 1. is implemented) attempt per 48h. I'm not entirely sure if I missed that information because it isn't out there (yet), or because I did read attentively enough. Either way, thanks you again. I'll try to go through the process again when i'm sure 48h have passed and will let you know if I run into any more problems

**Comment by sndurkin** [comment]
I'm reopening this as I added some action items for myself to improve this flow

**Comment by Arriu** [comment]
48h have passed and I have successfully resent the verification email. However, I i'm still getting the same error message.

Verification failed
The provided signature was invalid, which is usually caused from the local data on your browser being cleared or by using a different browser from the one you registered with. Please open the link from your verification email in the same browser that you used to register.

I was wondering if it would be possible to remove my email from the database so I can try signing up "fresh" and replicate exactly what I did when I made my 2nd account?

**Comment by sndurkin** [comment]
@Arriu you can actually re-register with the same email address, and the browser should create a new identity for you to verify the (new) email token with. You will have to wait another 48 hours since your last email was sent, or ask @dajohi to reset your registration token to do it before the 48 hours are up.
