### ISSUE TITLE
Work/jobs page

### ISSUE THREAD

**Issue by RichardRed0x** [decred/politeiagui#747]
What about adding a jobs/opportunities page somewhere on proposals.decred.org? This could inform people about the various opportunities to work on the project and offer some signposting for where to get started.

I am thinking about a simple page that lists sub-projects or programs which are looking for contributors - what kind of work is needed, what the sub-project is about. Something like this [list of Decred repositories](https://github.com/RichardRed0x/decred-on-github), but project-based.

**Comment by xaur** [comment]
This is interesting and can go pretty deep. Let me unroll some random thoughts triggered by this idea.

To me this looks like the next step of Politeia evolution to support "smaller" scale workflows, compared to proposals. I hope proposals will be quite "big" so that stakeholders will not become apathetic by micro-managing hundreds of small proposals.

Terminology: I like the world opportunity because it is more rich and less boring than "job", although job is much shorter and has less of the "business speak" attached to it. And of course this is subjective and depends on what the word "job" means to people (I'm proud of my current job ;))

Currently the list of opportunities is implicit: people surf the Decred world, find work that interest them, learn, start hacking, demonstrate they are capable and start billing. This serves as a nice filter for bullshit and inefficiency. But a list of opportunities does not necessarily conflict with existing setting. A job listing could be an entry point to the existing process of proving yourself, but one that is explicit and much easier to discover.

Somebody has to manage the list of jobs and keep it up to date. Create new opportunities, update existing and delete obsolete ones. The best positioned people to produce opportunities are product owners and lead developers who see where more hands would improve performance of the project.

Jobs can be unpaid and paid, but unpaid work is a chance to show yourself that can lead to paid work if stakeholders find it useful.

@noahpierau has recruiting experience and could possible comment on this.

_P.S. Micro-proposals are an interesting topic worth exploring._

**Comment by noahpierau** [comment]
The way it has worked so far: 1) people show up; 2) they get involved with a task they are passionate about; 3) they get reviews and improve; 4) they become part of Decred. This model has worked surprisingly well, we have attracted great people. You two are the living examples of that! 

A work/job page is very different from this approach. Honestly, I don't think it's a good idea for an open source project such as Decred. It will attract a lot of people who are used to the corporate way of working and are looking for a way to pay their bills. I've dealt with 100s of applicants via https://angel.co/decred and only a few of them showed up on Slack (and only a few of those actually contributed). It cost me a lot of time, with relatively little reward for the project. 

To me it makes more sense that our corporate contractors (or the people who submitted a proposal to the community) do the recruitment / hiring themselves.

**Comment by RichardRed0x** [comment]
I don't see it as really changing the 4-step process you outline @noahpierau, just a list of the things people could work on and what kind of work needs doing.

I was thinking that maintaining it would be mostly down to the people who lead on projects that are "recruiting" - if you want more people to approach you or try to get involved, list the work on this page.

It would make it easier for people who are less familiar with Decred to discover what the relevant opportunities for them might be. There's an argument to be made that making such discovery easier is bad, because the barrier mostly stops people who are ultimately not that interested or useful. I don't know how many people try to get involved but give up or produce work which is sub-standard, if that's a significant problem already then a page like this would make it worse. For sub-projects that don't tend to attract many potential contributors, a page like this could be useful if the root of the problem is that suitable people don't know the opportunity exists.

**Comment by xaur** [comment]
Before adding any code to Politeia, this concept can be tested by emulating it on e.g. a GitHub page. It would be a list of "position"-like entities that list places where help is most wanted right now. The maintainer would need to keep to keep an eye on projects, keep in touch with project leads (some might want to minimize their time spent on this) and keep the list updated. Now if you only could find a maintainer... :)

**Comment by s-ben** [comment]
Data point from someone who recently went through the current process (learned/hacked for ~8 weeks, started a couple weeks ago as part-time contractor, working on doco; digging it so far, hope to continue). For one, I do remember seeing a job list early on. The [Contributor Compensation](https://docs.decred.org/advanced/contributor-compensation/) in dcrdocs linked me to the [Becoming a Contractor](https://blog.decred.org/2017/07/25/Decred-Recruiting/) blog post, which, even though it's a year and three months old now, captures well the spirit of Decred and the basic process I experienced. There is a list of 'Current Roles to Fill' at the end though, and I remember thinking that was current until I later revisited it. 

I both appreciate the idea of a job board (or other mechanism), and also see its potential pitfalls. Right now, for instance, I'm stalled on my main project and just kind of "scouting" for work. It feels a bit like being a freelancer pitching clients. There's a lot of uncertainty, time I can't bill for (e.g. this comment), and learning this new structure of "employment". I find it all fascinating, as I think DAEs are the future. I'm also following the writings of @RichardRed0x and others with interest. I like the proposed contractor approval process. 

The addition of new, more granular structures/mechanisms of recruiting and coordination is particularly exciting. That piece seems like the holy grail. At the same time, it's easy to see how many ideas in this area could fail or be misaligned with Decred's mission. I think Decred's process of slow iteration when automating makes a lot of sense. In addition to a job board, I would throw out the ideas of a bounty system (already proliferating in the crypto space, if spammy most of the time), and tipping/donation/gift economy (which is basically what funds Monero development).

**Comment by RichardRed0x** [comment]
@xaur I don't think it really needs any code, a GitHub page should be fine for this purpose. The problem is, why would anyone set it up or maintain it unless there's somewhere to put it where it will be seen by the intended audience (people who are relatively new to Decred and considering how they could contribute)?

The role of the maintainer for this, as I see it, would just be taking requests from people who run sub-projects to add or edit an entry for their sub-project - either by approving PRs or by making the PRs in response to written requests.

**Comment by xaur** [comment]
@RichardRed0x would it then work for decred.org (e.g. decred.org/jobs) instead of the politeia website?

Re maintaining, ideally yes, the maintainer is just a "human interface" to the job list and doesn't need to actively follow and ping the leads. Maybe with the job list it will be different from events.

**Comment by RichardRed0x** [comment]
@xaur yeah I think it could work fine on decred.org, maybe with a link from the proposals.decred.org sidebar.

**Comment by ZeroASIC** [comment]
I agree that it would make more sense on decred.org.  I was thinking of creating a page about getting involved with the project in a more general sense.  The specifics of what people can work on could be linked from there.  It might be beneficial to include some of the content from the blog post with a link to the larger text and do the same for specific roles that Decred is in need of.  Instead of calling it a jobs page I was thinking it should be about getting involved instead of getting hired.  It could have several links to additional content about specific projects current needs on docs.decred.org or github, like the document @RichardRed0x started.  Maybe decred.org/involvement or decred.org/getinvolved would be more appropriate given the non-corporate context of the whole thing.

In addition to that I think a task board of some type, like @s-ben suggested, could be beneficial.  I think this functionality already exists in github in the projects section and is in use by decred/dcrdata (https://github.com/decred/dcrdata/projects/1).  Important items that the existing project members want done based on the priorities of the project could be added and managed there with links from decred.org/involement.  There is other software for this though and might have some additional functionality.  Maybe listing bounties on specific things would help them get done faster too.

**Comment by ZeroASIC** [comment]
Someone from reddit is working on a proposal for a bug bounty system.  Some of the details can be found here: https://www.reddit.com/r/decred/comments/9sri0b/bug_bounty_politeia_funding_proposal/

**Comment by tiagoalvesdulce** [comment]
Closing this because the discussion should be moved to decred/dcrweb#423.
