### ISSUE TITLE
Feature Request: Revision Diffs

### ISSUE THREAD

**Issue by davecgh** [decred/politeiagui#754]
Whenever there is an update to a proposal, it would be highly beneficial to see a diff of what changed similar to how github does it for pull requests, issues and comments.

For example, here is a comment with two edits (the initial creation and a modification):

![image](https://user-images.githubusercontent.com/2115102/47263075-75808880-d4bf-11e8-9feb-c331d044dc5f.png)

The first change (initial creation):

![image](https://user-images.githubusercontent.com/2115102/47263068-410ccc80-d4bf-11e8-93a8-43f82ef2af08.png)

The modification:

![image](https://user-images.githubusercontent.com/2115102/47263072-5c77d780-d4bf-11e8-9ce6-3c005d9df11c.png)

**Comment by brunobraga95** [comment]
That is interesting, I could work on that.

After a quick search I havent found something that already does it, I will try to look more and see what I find.

**Comment by brunobraga95** [comment]
I found something.

One thing to notice is that current proposals have thousands of words (most recent one I checked have more than 3 thousand). Let's solve this in the client side for now first because it is simpler and secondly not to fall into early optimization, but apparently the best diff algorithm is not linear, depending on how different the two strings are it may hit something close to N square (which then would be a problem for the client). The other approach could be doing it in the server side and play with some kind of caching where we would store maybe the 3 most recent edition (future).

Anyways, I will work on it.

Interesting paper I found http://www.xmailserver.org/diff2.pdf
the implementation I found: https://github.com/kpdecker/jsdiff (which implements the algorithm described above).

**Comment by RyanZim** [comment]
I find this to be extremely important. For example, on https://proposals.decred.org/proposals/c68bb790ba0843980bb9695de4628995e75e0d1f36c992951db49eca7b3b4bcd, version 2 is pretty clearly an addendum to the end of the proposal. However, if the author was evil (which I don't think Richard-Red is), they could try to slip some change to the body in the same edit, substantially changing the meaning of the proposal. If no one noticed, and the proposal was approved by the stakeholders, that'd be a sticky situation.

**Comment by brunobraga95** [comment]
working on it.

**Comment by xaur** [comment]
I wonder if it is possible to build a diff link to GitHub repository where Pi's public data is stored.

**Comment by marcopeereboom** [comment]
This was implemented.
