### ISSUE TITLE
Show full vote listing and allow searching by ticket address

### ISSUE THREAD

**Issue by matheusd** [decred/politeiagui#803]
This would allow users to see if their vote has actually been computed.

Ideally, it should show (or allow a local search) of votes by ticket address, since that's the most common way for users to identify their voting rights (vs the actual commitment address which usually is a bit harder for users to grasp).

This might require internal changes in politeia to provide this info.

It's important to note that, due to privacy reasons, this page should *not* request/search for single tickets in the server: it should provide all voting data and allow the client to locally search for their own tickets.

**Comment by raedah** [comment]
Similarly, this data could also be made consumable by dcrdata so that we could list off vote choices for an address. We could display vote stats per proposal such as we are already doing for on chain agendas, https://explorer.dcrdata.org/agendas . This work load would be a good fit for dcrdata because we already have a postgresql backend and server infrastructure handling large queries as well as the charting infrastructure in place.

**Comment by thi4go** [comment]
Working on this issue, guys.

**Comment by fernandoabolafio** [comment]
closed on #899
