### ISSUE TITLE
Add "Abandoned" proposals list

### ISSUE THREAD

**Issue by lukebp** [decred/politeiagui#889]
We've added a new proposal status called "abandoned".  A public list in the proposals view needs to be added to displays these abandoned proposals.

Abandoned proposals will have a proposal status code of 6 and will be included in the `/proposals/vetted` response.

We also need to make sure that the gui enforces these rules for abandoned proposals:
- Doesn't allow the author to authorize a vote 
- Doesn't allow edits
- Doesn't allow comments or comment upvotes/downvotes

**Comment by fernandoabolafio** [comment]
@xaur  I agree with your point that "Obsolete" or "Deprecated" would be a better wording for that. Another thing I think is that would be better to place those proposals in another route instead of keeping in the index page. The reason for that is to reduce the spotlight for proposals that have been abandoned. Another argument supporting that is that the tabs group the proposals by their voting status and not by their "review status".

**Comment by xaur** [comment]
@fernandoabolafio I expect Obsolete proposals will pile up as time goes, same for low quality proposals. Therefore I suggest they are lazy loaded regardless of the presentation approach.

I disagree they must be removed from the index/default page entirely. They are still vetted proposals, logically at the end of their lifecycle (via the `new -> obsolete` transition). There must be a mention of them and the counter. A tab is the best because it is consistent with other tabs. As an end user, I don't care much about the internal semantics of tabs ("voting status" vs "review status"). To me they are filters that I switch between.

Talking about routes, each tab must have its own route anyway, but that's perhaps a separate feature.

**Comment by lukebp** [comment]
> "Abandoned" suggests it is the action by the author (who abandons proposal), while in reality it is the action by admin who declares it abandoned. How about "Obsolete" or "Deprecated"?

This was changed from "deprecated" to "abandoned" per jy-p and moo31337.  Changing it again would require a conversation with them.

> Related question: is there a standard rule to become abandoned?

There will be, we just don't know exactly what the rules are yet, so for now, an admin can mark a public proposal as abandoned at their discretion.  The code will be updated once the rules have been formalized.

**Comment by xaur** [comment]
There was a long discussion started [here](https://riot.im/app/#/room/!OfChXgczrIlpEZSFAv:decred.org/$154238946818288XjEKG:decred.org) that provided clear reasons to keep it Abandoned. Then it [here](https://riot.im/app/#/room/!MIGqWXfLFBwhipPKYL:decred.org/$154237919818098bsTbF:decred.org). Names discussed were: Abandoned, Obsolete, Stale, Deprecated, Removed and some others. No solid decision was made, therefore I withdraw my idea and apologize for distraction.

Removed gained some support but it is more abstract (on purpose) to cover two resolutions: 1) Abandoned by author, 2) Removed by admins to prevent the wasteful vote on low quality/junk/too small proposal. This would be a separate feature.

**Comment by fernandoabolafio** [comment]
I moved the terminology issue from "deprecated" to "abandoned" to here: https://github.com/decred/politeiagui/issues/900.
I am closing this issue as it was more related to the feature integrated into the GUI.
