### ISSUE TITLE
Extract docs from modals into linkable pages, source them from .md

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#947]
I suggest changing all documentation available in the modals to separate pages that can be linked to. Such pages can even work without javascript.

Ideally, the single source of truth for the docs are Markdown files. It is easier to engage copy writers to change Markdown files than HTML or JS files. Then you can build .html and .js from the .md.

**Comment by camus-code** [comment]
Really like this suggestion here. When we eventually get to the redesign of PI it will also make for migrating this content a lot simpler.

I'll pick this one up

**Comment by s-ben** [comment]
Was chatting with @camus-code about this. We agreed that, as a first step, we can just update the modal copy with more polished copy created for Pi docs on dcrdata. PR for said copy here,
https://github.com/decred/dcrdocs/pull/758 

We may also want to remove some copy from the modal, and just link to its equivalent in dcrdocs. For instance, link externally to the example proposals, and possibly the proposal guidelines. The md files in dcrdocs can serve as the source of truth, to avoid content diverging over time. We may also just want to just remove the modal entirely and point to the docs. Or, during/after the redesign, create separate pages in Pi for this content, instead of having it all in the modal, where it's a bit cramped.

**Comment by xaur** [comment]
Good way to get it started @s-ben . All I want is be able to say "hey before blindly submitting a prop make sure to check these guidelines <link>".

I like the idea to remove the docs entirely from politeia and have all in dcrdocs for now. The modal improves the UX by having the info accessible a few seconds faster, but the price is high -- we have two overlapping and diverging sets of documents to maintain. And no direct links.

**Comment by s-ben** [comment]
@xaur , @camus-code , now that the new [Pi docs](https://docs.decred.org/governance/politeia/politeia/) are live on dcrdocs, I agree we should just get rid of the modal and send people there. I used the copy in the pi modal as the basis for the new Pi pages, and all the info in the modal is covered there (plus more). 

Two potential issues:

- If we replace the 'Learn More about Politeia' link on the main page with a link to the [Pi docs](https://docs.decred.org/governance/politeia/politeia/), won't the user get the scary WARNING EXTERNAL LINK message? 
- To address your concern about people not reading the docs before blindly submitting proposals, perhaps we could add copy like what you suggest above on the [proposal submission page](https://proposals.decred.org/proposals/new)?

**Comment by camus-code** [comment]
@s-ben Pi dcrdocs look great, nice work. I'm in favor of just routing people to the new link as well.

As for your concerns:

-There are no external link warnings when linking to internal (.decred) sites so that will be a non issue

-We already have a link on the submit proposal page that reads "Learn how to format your proposal" that opens up the modal. Unless you're not a fan of this copy, I think we can just keep it as is and instead link it to dcrdocs

**Comment by s-ben** [comment]
Had missed the "Learn how to format your proposal" link. It is really small though, and not placed particularly prominently. Others might miss it as well. Perhaps we want to make this more visible in the UI? As for that linking to the modal, I would assume we'd want to change it to a link to the docs for the same reason we change the 'Learn More about Politeia' link. Perhaps with the "Learn how to format your proposal" link, we can link to the [proposal guidelines](https://docs.decred.org/governance/politeia/proposal-guidelines/) page, instead of the main pi docs page like I suggested for the "Learn how to format your proposal" link?

**Comment by camus-code** [comment]
Yeah I agree it is easy to miss. I'll definitely tweak it a bit and work on making it more visible. Linking to the actual guidelines is a good idea as well

PR should be in within the hour

**Comment by xaur** [comment]
I suggest to avoid introducing any copies that must be maintained in sync. Have the UX to route the user through the link, or even dynamically load and render the markdown file.
